### ISSUE TITLE
Many of the containers fail to stay started

### ISSUE THREAD

**Issue by dillfrescott** [mozilla/hubs-compose#20]
some say:

```
sh: 1: webpack: not found
```

**Comment by bryanenders** [comment]
Have you already initialized the services with `bin/init`?

**Comment by dillfrescott** [comment]
Ah, yes, and I even tried it multiple times thinking maybe it left something incomplete.

**Comment by dillfrescott** [comment]
I am sorry I was using a vps to run the project so I terminated the vps because I had to pay for it. I can try to run it again sometime and send you the logs...

**Comment by h3d-longnsp** [comment]
Have you tried to install both mutagen and mutagen-compose? Mutagen-compose needs a matching version of Mutagen [installed](https://mutagen.io/documentation/introduction/installation) and available in your path.

**Comment by dillfrescott** [comment]
Yes, they were both installed and on the system path

**Comment by h3d-longnsp** [comment]
What vps did you use?
Also you should try it first on local machine as I had tried it and had no problems. The point of using docker compose is to have consistent env across devices so I really dont understand the `missing webpack` part.

**Comment by dillfrescott** [comment]
I used one from `serverspace.us`. I've kinda moved on from this project anyways.

**Comment by bryanenders** [comment]
Closing until this issue can either be reproduced or logged

**Comment by dillfrescott** [comment]
reproduced this again on a local machine. same issue
