### ISSUE TITLE
Trouble creating admin account

### ISSUE THREAD

**Issue by h3d-longnsp** [mozilla/hubs-compose#22]
- I dont know if this is a bug or not as I can run this command when I installed the stack on local (not using docker compose) but when `bin/up` finished and registered first account, I can't run this command in `bin/iex` from `./services/reticulum`  to made it an admin account `Ret.Account |> Ret.Repo.all() |> Enum.at(0) |> Ecto.Changeset.change(is_admin: true) |> Ret.Repo.update!()`. The console output this error: 
![image](https://user-images.githubusercontent.com/99666567/208610446-d078cfce-0d19-4d7e-8f57-bd77d3ff6091.png)
- My solution was alter the data directly in the db container:  run `bin/psql` from `./services/reticulum` then run `UPDATE accounts SET is_admin = 't' WHERE is_admin = 'f';` (assuming you only have 1 account)
![image](https://user-images.githubusercontent.com/99666567/208611489-4210c7f9-5f5f-427a-a36a-a0f940572db8.png)

**Comment by bryanenders** [comment]
IEx doesn’t load local modules by default. The `-S` flag finds and executes the given script in `$PATH`. When you give it the `-S mix` options, it starts the local mix project and makes those modules available. Try **$** `./iex -S mix`.

Your solution is a good alternative!
