### ISSUE TITLE
error while executing ./bin/init

### ISSUE THREAD

**Issue by hassanayoub1985** [mozilla/hubs-compose#24]
Hi,

Initializing Dialog

[+] Running 2/2
 ⠿ Container hubs-compose-mutagen-1  Recreated                                                         0.4s
 ⠿ Mutagen                           Terminated                                                        0.4s
[+] Running 2/2
 ⠿ Container hubs-compose-mutagen-1  Healthy                                                           3.4s
 ⠿ Mutagen                           Started                                                           2.4s
npm ERR! Cannot read property '@sitespeed.io/throttle' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-05T13_34_49_590Z-debug.log
[+] Running 4/4
 ⠿ Container hubs-compose-db-1       Removed                                                           0.2s
 ⠿ Container hubs-compose-mutagen-1  Removed                                                           0.4s
 ⠿ Mutagen                           Terminated                                                        0.4s
 ⠿ Network mozilla-hubs              Removed

**Comment by Tz-H** [comment]
I fixed it by updating `bin/init` file to add `npm cache clear --force` before calling `npm ci` for Dialog:

```bash
#======HERE
echo -e ${prefix}Initializing Dialog$suffix &&
mutagen-compose -f "$composefile" run --rm dialog sh -c '[ -d "node_modules" ] || npm cache clear --force || npm ci' && 
```

**Comment by fsoft72** [comment]
The @Tz-H  fix worked for me too

> I fixed it by updating `bin/init` file to add `npm cache clear --force` before calling `npm ci` for Dialog:
> 
> ```shell
> #======HERE
> echo -e ${prefix}Initializing Dialog$suffix &&
> mutagen-compose -f "$composefile" run --rm dialog sh -c '[ -d "node_modules" ] || npm cache clear --force || npm ci' && 
> ```

**Comment by bryanenders** [comment]
Was this error encountered the first time running `bin/init` or during a subsequent run?

**Comment by giangduong** [comment]
I got the same issue. Apply [Tz-H](https://github.com/Tz-H) solution will fix the bin/init execution but when i run bin/up, i do not see following containers up and running:
1. Dialog
2. hubs client
3. hub admin

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/8393739/220886396-f341ec58-0c3f-4555-9061-3e232b9c7acd.png">

I got this error message when go to https://hubs.local:4000/ 

"Missing file admin.html. Please try again."

**Comment by bryanenders** [comment]
Unfortunately this solution doesn’t do what you likely think it does. The double pipe in `npm cache clear --force || ` has the effect of skipping the `npm ci` call altogether! The root cause of the issue appears to have been [an update to Dialog](https://github.com/mozilla/dialog/commit/022cae14eb7dda4c27eeaefae084a120ff5316b9) which added a Python dependency. A fix is forthcoming.

To answer my own question, this issue is occurring where `node_modules` doesn’t already exist.
