### ISSUE TITLE
services/reticulum/priv/dev-ssl.cert not found

### ISSUE THREAD

**Issue by Thiago-Innovate** [mozilla/hubs-compose#4]
Probably I miss-understood some points, 

I am just trying to run the "./bin/init" and "./bin/up" or even trying to run direct the command "docker compose up", but I still getting this error.

I should generate this "dev-ssl.cert" by myself or is there any other thing I could do to run the hubs locally?

Thanks in advance

I am using mac-book pro m1

**Comment by bryanenders** [comment]
Fixed in https://github.com/mozilla/hubs-compose/pull/9
