### ISSUE TITLE
Incorrect path for services folder in init script

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs-compose#5]
This variable:

`servicesdir=$(readlink -f $basedir/../services)
`

resolves as blank on my installation (on MacOS), which means that the clone path in this line:

`git clone https://github.com/mozilla/reticulum.git $servicesdir/reticulum
`

is `/reticulum`, which can't resolve because it is root.

I'm guessing that there is some sort of convention to map a services folder in the parent folder?

**Comment by bryanenders** [comment]
Good catch, @rawnsley! The fix should be merged shortly.

**Comment by bryanenders** [comment]
Fixed in https://github.com/mozilla/hubs-compose/pull/9
