### ISSUE TITLE
Unable to get the admin pages to work

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs-compose#8]
I've got the normal client pages working and connecting fine, but I'm having problems with the admin pages, which I've never actually got running locally outside of docker, so perhaps I'm missing a few key steps.

The first problem is that it can't read the _schema.toml_ file because [it appears to be expecting](https://github.com/mozilla/hubs/blob/408c09e24768c927fe32bf599c8178b24a60a691/admin/src/admin.js#L255) the hubs server to be providing it on the same port (as it does in production), but in this development environment the admin pages are hosted on hubs.local:**8989** and the hubs pages are hosted on hubs.local:**8080**. It's possible the implications of this failure are just cosmetic.

The second problem is that the page doesn't seem to be recognizing that I'm signed in with any sort of credentials, despite the sign in process working fine on the hubs pages. It appears that [store.state.credentials](https://github.com/mozilla/hubs/blob/408c09e24768c927fe32bf599c8178b24a60a691/admin/src/admin.js#L277) is blank for reasons unknown.

When the credential check fails, it once again [falls back on the assumption](https://github.com/mozilla/hubs/blob/408c09e24768c927fe32bf599c8178b24a60a691/admin/src/admin.js#L286) that hubs is co-hosted on the same port for the redirection, which fails. This isn't really an issue that needs addressing though.

Sorry for spamming the issues today, but this new docker-compose is exactly what I've been wanting for ages and I'm very excited to dive in :-)

**Comment by rawnsley** [comment]
The root of the authentication problem is this common theme: the admin pages are assumed to be co-origin with the hubs client pages and expect to be able to access _localStorage_ for things like credentials.

An ugly workaround for this is to copy-and-paste the settings from the client to the admin pages, based on [this method](https://stackoverflow.com/a/46128830/671393):

From the client page: `JSON.stringify(localStorage); `

Then right-click copy the result using **Copy string as Javascript literal** (Chrome option)

Then paste into the admin pages like this: `Object.assign(localStorage,JSON.parse(_settings-string_));`

Suggestions welcome on something a bit less hacky.

**Comment by keianhzo** [comment]
I don't seem to have issues connecting to the admin. 

I just open https://hubs.local:4000/admin and as long as the signed account has admin permissions you should be good. If not (that might be the case after a fresh start) make sure you update your connected account and enable the `is_admin` flag:

<img width="962" alt="Screenshot 2022-10-27 at 15 25 45" src="https://user-images.githubusercontent.com/837184/198296979-cbf3d70f-c52a-4b6f-9586-4be7823901b6.png">

**Comment by rawnsley** [comment]
@keianhzo That works! Thanks for the tip. It might be worth putting it in the readme.
